name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
      

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node: [ 20 ]

    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    
    - name: Set up Node.js | ${{ matrix.node }}
      uses: actions/setup-node@v4.4.0
      with:
        # node-version: ${{ matrix.node }}
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies and run tests
      run: |
           npm install
           npm run test

    - name: Get Tag
      id: generate_tag
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    # Login no Docker Hub usando variáveis de repositório
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ vars.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Build and push Docker images
    #   uses: docker/build-push-action@v6.18.0
    #   with:
    #     push: true
    #     tags: ${{ vars.DOCKERHUB_USERNAME }}/rocketseat-ci-api:${{ steps.generate_tag.outputs.sha }}, ${{ vars.DOCKERHUB_USERNAME }}/rocketseat-ci-api:latest

    # Outra alternativa para o login no Docker Hub
    # - name: Build Docker image
    #   run: |
    #     docker build -t ${{ vars.DOCKERHUB_USERNAME }}/rocketseat-ci-api:${{ steps.generate_tag.outputs.sha }} .
    
    # - name: Push Docker image
    #   run: |
    #     docker push ${{ vars.DOCKERHUB_USERNAME }}/rocketseat-ci-api:${{ steps.generate_tag.outputs.sha }}