name: CI

on:
  push:
    branches:
      - main
      

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node: [ 20 ]

    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    
    - name: Set up Node.js | ${{ matrix.node }}
      uses: actions/setup-node@v4.4.0
      with:
        # node-version: ${{ matrix.node }}
        node-version: '20'
        cache: 'yarn'
    
    - name: Install dependencies and run tests
      run: |
           yarn
           yarn run test

    - name: Get Tag
      id: generate_tag
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ${{ vars.DOCKERHUB_USERNAME }}/rocketseat-ci-api:${{ steps.generate_tag.sha }} .
    
    - name: Push Docker image
      run: |
        docker push ${{ vars.DOCKERHUB_USERNAME }}/rocketseat-ci-api:${{ steps.generate_tag.sha }}