name: CI

on:
  push:
    branches:
      - main
      

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [16,18,20]

    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    
    - name: Set up Node.js
      uses: actions/setup-node@v4.4.0
      with:
        node-version: 20
        cache: 'yarn'
    
    - name: Install dependencies and run tests
      run: |
           yarn
           yarn run test
