name: CI

on:
  push:
    branches:
      - main
      

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 20 ]

    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    
    - name: Set up Node.js | ${{ matrix.node }}
      uses: actions/setup-node@v4.4.0
      with:
        node-version: ${{ matrix.node }}
        cache: 'yarn'
    
    - name: Install dependencies and run tests
      run: |
           yarn
           yarn run test

    - name: Build Docker image
      run: |
           docker build -t rocketseat-ci-api:latest .
